# Generated by Django 6.0.1 on 2026-01-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='task_instance',
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='additional_parameters',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='file_name',
            field=models.CharField(default='test_file', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task_manager.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='working_directory',
            field=models.CharField(default='dir_1', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
