# Generated by Django 6.0.1 on 2026-01-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_remove_program_task_instance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program',
            new_name='name',
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(default='slug-change'),
            preserve_default=False,
        ),
    ]
