# Generated by Django 6.0.1 on 2026-01-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_rename_program_program_name_program_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
