# Generated by Django 6.0.1 on 2026-02-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_program_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
