# Generated by Django 6.0.1 on 2026-02-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_taskinstance_end_time_taskinstance_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='pid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
