# Generated by Django 6.0.1 on 2026-02-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_alter_taskinstance_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
