# Generated by Django 6.0.1 on 2026-02-07 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_alter_taskinstance_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='state',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('KILLED', 'Killed'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='RUNNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='working_directory',
            field=models.CharField(default='C:\\Users\\blaze\\OneDrive\\Plocha\\Programovani', max_length=500),
        ),
    ]
