# Generated by Django 6.0.1 on 2026-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_taskinstance_state_alter_taskinstance_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemresources',
            name='date',
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='state',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('KILLED', 'Killed'), ('FINISHED', 'Finished'), ('FAILED', 'Failed'), ('WAITING', 'Waiting')], default='RUNNING', max_length=20),
        ),
    ]
