# Generated by Django 6.0.1 on 2026-02-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0010_systemresources_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemresources',
            name='elapsed_seconds',
            field=models.FloatField(default=60),
            preserve_default=False,
        ),
    ]
