# Generated by Django 6.0.1 on 2026-02-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_systemresources_elapsed_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemresources',
            name='created_at',
        ),
    ]
