# Generated by Django 6.0.1 on 2026-02-16 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0012_remove_systemresources_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemresources',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
